version: 1
sequences:
- protein:
    id: [evgS_A, evgS_B]
    sequence: MKFLPYIFLLCCGLWSTISFADEDYIEYRGISSNNRVTLDPLRLSNKELRWLASKKNLVIAVHKSQTATLLHTDSQQRVRGINADYLNLLKRALNIKLTLREYADHQKAMDALAEGEVDIVLSHLVTSPPLNNDIAATKPLIITFPALVTTLHDSMRPLTSPKPVNIARVANYPPDEVIHQSFPKATIISFTNLYQALASVSAGHNDYFIGSNIITSSMISRYFTHSLNVVKYYNSPRQYNFFLTRKESVILNEVLNRFVDALTNEVRYEVSQNWLDTGNLAFLNKPLELTEHEKQWIKQHPNLKVLENPYSPPYSMTDENGSVRGVMGDILNIITLQTGLNFSPITVSHNIHAGTQLSPGGWDIIPGAIYSEDRENNVLFAEAFITTPYVFVMQKAPDSEQTLKKGMKVAIPYYYELHSQLKEMYPEVEWIQVDNASAAFHKVKEGELDALVATQLNSRYMIDHYYPNELYHFLIPGVPNASLSFAFPRGEPELKDIINKALNAIPPSEVLRLTEKWIKMPNVTIDTWDLYSEQFYIVTTLSVLLVGSSLLWGFYLLRSVRRRKVIQGDLENQISFRKALSDSLPNPTYVVNWQGNVISHNSAFEHYFTADYYKNAMLPLENSDSPFKDVFSNAHEVTAETKENRTIYTQVFEIDNGIEKRCINHWHTLCNLPASDNAVYICGWQDITETRDLINALEVEKNKAIKATVAKSQFLATMSHEIRTPISSIMGFLELLSGSGLSKEQRVEAISLAYATGQSLLGLIGEILDVDKIESGNYQLQPQWVDIPTLVQNTCHSFGAIAASKSIALSCSSTFPEHYLVKIDPQAFKQVLSNLLSNALKFTTEGAVKITTSLGHIDDNHAVIKMTIMDSGSGLSQEEQQQLFKRYSQTSAGRQQTGSGLGLMICKELIKNMQGDLSLESHPGIGTTFTITIPVEISQQVATVEAKAEQPITLPEKLSILIADDHPTNRLLLKRQLNLLGYDVDEATDGVQALHKVSMQHYDLLITDVNMPNMDGFELTRKLREQNSSLPIWGLTANAQANEREKGLSCGMNLCLFKPLTLDVLKTHLSQLHQVAHIAPQYRHLDIEALKNNTANDLQLMQEILMTFQHETHKDLPAAFQALEAGDNRTFHQCIHRIHGAANILNLQKLINISHQLEITPVSDDSKPEILQLLNSVKEHIAELDQEIAVFCQKND
    msa: empty
- ligand:
    id: [ATP_A, ATP_B]
    ccd: ATP
constraints:
- pocket:
    binder: ATP_A
    contacts: [[evgS_A, 152]]
- pocket:
    binder: ATP_B
    contacts: [[evgS_B, 152]]
